title: WANGHO LIT's Homepage
page-top-title: WANGHO LIT
top-section-bg-text: Science in Computing
home-subtitle: WANGHO LIT&ensp;|&ensp;列泓昊
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
